### PR TITLE
feat: support `.mbt` extension for moonbit language

### PR DESCRIPTION
**Pull request by DiamondMofeng**
HI! 

Recently I have been focusing on a new programming language called Moonbit. It seems that moonbit's repository also needs a github action to check license header.

I happened to remember today that hawkeye was used in the greptime repository. So I just gave it a try.

Unfortunately, it seems that hawkeye currently does not know how to handle the moonbit code.

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
Thank you and this looks correct. Do you verify it locally that every thing works as expected?

Perhaps build locally and test against the binary is enough.

**Comment by DiamondMofeng** [comment]
> Thank you and this looks correct. Do you verify it locally that every thing works as expected?
> 
> Perhaps build locally and test against the binary is enough.

Thanks for your quick reply.

I am now on a laptop without a rust compiler. Maybe I'll just install one and check later tonight.

**Comment by tisonkun** [comment]
@DiamondMofeng Cool. This patch won't affect other user cases so as long as you can confirm it I'm OK to merge.

Just I'm too unfamiliar with moonbit to try it out.

**Comment by DiamondMofeng** [comment]
Just fixed a typo and it works well now. Ready to merge.

**Comment by tisonkun** [comment]
Thank you!

**Pull request merged**
