### PR TITLE
fix: correct default config file path for multi-module project

### LINKED ISSUE #94: Refactor the Maven plugin as an aggregator plugin
Ref - https://cwiki.apache.org/confluence/display/MAVENOLD/Aggregator+Plugins

Otherwise, for multiple module project, the configuration file path will be resolved as per project basedir and cause un-intuitive result:

```
[INFO] --------------------< io.korandoru.hawkeye:hawkeye >--------------------
[INFO] Building HawkEye 3.3.1-SNAPSHOT                                    [1/6]
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- hawkeye:3.3.0:check (default-cli) @ hawkeye ---
[INFO] Checking license headers... with cfg: /Users/tison/Brittani/hawkeye/licenserc.toml
[WARNING] Processing unknown file: /Users/tison/Brittani/hawkeye/action.yml.bak
[INFO] No missing header file has been found.
[INFO] 
[INFO] -----------------< io.korandoru.hawkeye:hawkeye-core >------------------
[INFO] Building HawkEye :: Core 3.3.1-SNAPSHOT                            [2/6]
[INFO]   from hawkeye-core/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- hawkeye:3.3.0:check (default-cli) @ hawkeye-core ---
[INFO] Checking license headers... with cfg: /Users/tison/Brittani/hawkeye/hawkeye-core/licenserc.toml
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for HawkEye 3.3.1-SNAPSHOT:
[INFO] 
[INFO] HawkEye ............................................ SUCCESS [  0.240 s]
[INFO] HawkEye :: Core .................................... FAILURE [  0.001 s]
[INFO] HawkEye :: Command ................................. SKIPPED
[INFO] HawkEye :: Distribution :: Command Line Interface .. SKIPPED
[INFO] HawkEye :: Distribution :: Native Image ............ SKIPPED
[INFO] HawkEye :: Maven Plugin ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.318 s
[INFO] Finished at: 2023-08-30T20:59:25+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] /Users/tison/Brittani/hawkeye/hawkeye-core/licenserc.toml (No such file or directory)
```

### PR DESCRIPTION
**Pull request by spencercjh**
TRY TO RESOLVE #94 although I have no idea about the maven plugin's best practice...

Reference: https://stackoverflow.com/questions/1012402/maven2-property-that-indicates-the-parent-directory

### CODE REVIEW

**Review by tisonkun — COMMENTED** [review]
This approache has an issue that for multi-module project that is no violation, we'll execute the check task N times where N=number of pom.xml (modules).

**Comment by spencercjh** [comment]
> This approache has an issue that for multi-module project that has no violation, we'll execute the check task N times where N=number of pom.xml (modules).

Sorry for not reading the maven aggregator docs carefully, so I should work on top of that branch of your commit?

**Comment by tisonkun** [comment]
I'm thinking of the proper solution. `license-maven-plugin` actually use an inline fixup to exclude submodules:

```java
  private String[] buildExcludes(final LicenseSet licenseSet) {
    List<String> ex = new ArrayList<>();
    ex.addAll(asList(licenseSet.excludes));
    if (project != null && project.getModules() != null && !aggregate) {
      for (String module : project.getModules()) {
        ex.add(module + "/**");
      }
    }
    return ex.toArray(new String[ex.size()]);
  }
```

**Comment by tisonkun** [comment]
But if we use aggregator, we can simply guide users not to configure the plugin into multiple modules but only the root. Let me fix up #94.

And yes you can PR against #94 so that we can co-author the PR.

**Comment by tisonkun** [comment]
I make some new changes in #94 and write a dedicated README for our expected usage. You may give it a review (even after merge).

**Pull request closed without merging**
