### PR TITLE
feat: add fail_if_updated and fail_if_unknown

### PR DESCRIPTION
**Pull request by tisonkun**

### CODE REVIEW

**Comment by tisonkun** [comment]
In this way, we can keep the compatibility and release a v5.5.0 instead.

**Comment by YuanYuYuan** [comment]
> @YuanYuYuan You may try out this patch with:
> 
> ```yaml
>       - uses: korandoru/hawkeye@main
>         with:
>           mode: format
>           args: --fail-if-updated=false
> ```
> 
> After it gets merged. Or `tisonkun/hawkeye@add-fail-if-updated` if before it merged.

Thanks! I think adding this argument is better and more general. :+1:

**Comment by tisonkun** [comment]
@YuanYuYuan OK. I'll release a v5.5.0 tomorrow. And alias it as v5.

**Comment by tisonkun** [comment]
@YuanYuYuan Released.

**Comment by YuanYuYuan** [comment]
> @YuanYuYuan Released.

That's great. Thanks!

**Pull request merged**
